require('dotenv').config();
const mongoose = require('mongoose');
const Sneaker = require('./models/Sneaker');

// Helper to generate sneaker entries
function makeSneaker(id, name, brand, price, origPrice, color, hex, style, category, desc, features, sizes, rating, reviews, isNew, isTrending, variants) {
  return {
    name, brand, price, originalPrice: origPrice, color, colorHex: hex, style, category,
    description: desc, features, sizes, rating, reviews, isNew, isTrending,
    stock: Math.floor(Math.random() * 200) + 20,
    colorVariants: variants,
    images: ['/images/sneakers/placeholder.png'],
  };
}

const stdSizes = [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 13];
const smSizes = [6, 7, 8, 9, 10, 11, 12, 13];

const sneakers = [
  // ─── NIKE (20) ──────────────────────────────────
  makeSneaker(1,'Air Nova X','Nike',15799,19099,'Black/White','#1a1a1a','street','Running','Ultra-responsive ZoomX foam and breathable Flyknit upper for street runners.',['ZoomX Foam','Flyknit Upper','React Midsole','Rubber Outsole'],stdSizes,4.8,342,true,true,[{name:'Black/White',hex:'#1a1a1a',secondary:'#ffffff'},{name:'University Red',hex:'#cc0000',secondary:'#1a1a1a'},{name:'Royal Blue',hex:'#1a3cc7',secondary:'#ffffff'}]),
  makeSneaker(2,'Jordan 1 Retro High','Nike',14899,null,'Chicago','#cc0000','street','Basketball','The iconic silhouette with premium leather construction.',['Premium Leather','Air-Sole Unit','Rubber Cupsole','Perforated Toe'],stdSizes,4.9,1204,false,true,[{name:'Chicago',hex:'#cc0000',secondary:'#ffffff'},{name:'Royal',hex:'#1a3cc7',secondary:'#1a1a1a'},{name:'Shadow',hex:'#555555',secondary:'#1a1a1a'}]),
  makeSneaker(3,'Dunk Low Panda','Nike',9999,null,'Black/White','#1a1a1a','street','Lifestyle','Clean two-tone styling on a comfortable low-profile silhouette.',['Leather Upper','Foam Midsole','Rubber Outsole','Padded Collar'],stdSizes,4.7,2341,false,true,[{name:'Black/White',hex:'#1a1a1a',secondary:'#ffffff'},{name:'Grey Fog',hex:'#b0b0b0',secondary:'#ffffff'},{name:'Green Glow',hex:'#34d399',secondary:'#ffffff'}]),
  makeSneaker(4,'Air Force 1 Low','Nike',9499,null,'Triple White','#ffffff','street','Lifestyle','Timeless style with durable leather and iconic Air cushioning since 1982.',['Full-Grain Leather','Encapsulated Air','Non-Marking Outsole','Perforated Toe'],[6,...stdSizes,14],4.8,5423,false,true,[{name:'Triple White',hex:'#ffffff',secondary:'#f0f0f0'},{name:'Triple Black',hex:'#0a0a0a',secondary:'#1a1a1a'},{name:'Wheat',hex:'#d4a654',secondary:'#8B6914'}]),
  makeSneaker(5,'Air Max 97 Silver Bullet','Nike',15399,null,'Metallic Silver','#c0c0c0','street','Lifestyle','Full-length visible Air unit and reflective 3M accents.',['Full-Length Air','3M Reflective','Synthetic Upper','Rubber Outsole'],stdSizes,4.7,789,false,true,[{name:'Metallic Silver',hex:'#c0c0c0',secondary:'#cc0000'},{name:'Triple Black',hex:'#0a0a0a',secondary:'#1a1a1a'}]),
  makeSneaker(6,'Nike SB Dunk Low Pro','Nike',9499,null,'Court Purple','#7c3aed','street','Skateboarding','Zoom Air insole for impact protection and grippy herringbone outsole.',['Zoom Air Insole','Suede/Leather Upper','Herringbone Outsole','Padded Tongue'],stdSizes,4.6,567,true,true,[{name:'Court Purple',hex:'#7c3aed',secondary:'#1a1a1a'},{name:'Chicago',hex:'#cc0000',secondary:'#ffffff'}]),
  makeSneaker(7,'Air Max 90','Nike',11599,null,'Infrared','#ff4444','street','Lifestyle','The AM90 with visible Air unit and iconic infrared colorway.',['Visible Air Unit','Leather/Mesh Upper','Rubber Waffle Outsole','Foam Midsole'],stdSizes,4.7,1890,false,true,[{name:'Infrared',hex:'#ff4444',secondary:'#1a1a1a'},{name:'Triple White',hex:'#ffffff',secondary:'#e0e0e0'}]),
  makeSneaker(8,'Air Jordan 4 Retro','Nike',18299,null,'Military Black','#1a1a1a','street','Basketball','Premium nubuck leather and mesh panels with visible Air cushioning.',['Nubuck Leather','Visible Air Unit','Mesh Panels','Herringbone Outsole'],stdSizes,4.8,923,true,true,[{name:'Military Black',hex:'#1a1a1a',secondary:'#555555'},{name:'Bred',hex:'#cc0000',secondary:'#1a1a1a'}]),
  makeSneaker(9,'Air Max Plus','Nike',14499,null,'Hyper Blue','#0099ff','street','Lifestyle','Tuned Air technology and gradient upper inspired by palm trees.',['Tuned Air','Gradient Mesh Upper','Rubber Outsole','TPU Overlays'],stdSizes,4.5,654,false,false,[{name:'Hyper Blue',hex:'#0099ff',secondary:'#1a1a1a'},{name:'Triple Black',hex:'#0a0a0a',secondary:'#1a1a1a'}]),
  makeSneaker(10,'Nike Vomero 18','Nike',13299,null,'Phantom/Sail','#f0ece6','sport','Running','ZoomX foam and responsive cushioning for everyday running comfort.',['ZoomX Foam','Engineered Mesh','Waffle Outsole','Plush Collar'],stdSizes,4.6,412,true,false,[{name:'Phantom/Sail',hex:'#f0ece6',secondary:'#c0bcb7'},{name:'Black/White',hex:'#1a1a1a',secondary:'#ffffff'}]),
  makeSneaker(11,'Nike Pegasus 41','Nike',11599,null,'Black/White','#1a1a1a','sport','Running','ReactX foam delivers 13% more energy return for everyday running.',['ReactX Foam','Flywire Cables','Engineered Mesh','Rubber Outsole'],stdSizes,4.7,2103,true,true,[{name:'Black/White',hex:'#1a1a1a',secondary:'#ffffff'},{name:'Volt',hex:'#ccff00',secondary:'#1a1a1a'}]),
  makeSneaker(12,'Blazer Mid 77','Nike',8699,null,'White/Black','#ffffff','casual','Lifestyle','Vintage basketball style with exposed foam on the tongue.',['Leather Upper','Vulcanized Sole','Exposed Foam','Herringbone Outsole'],stdSizes,4.5,1567,false,false,[{name:'White/Black',hex:'#ffffff',secondary:'#1a1a1a'},{name:'Sail/Green',hex:'#f5f0e6',secondary:'#2d5016'}]),
  makeSneaker(13,'Air Jordan 11 Retro','Nike',19499,null,'Cherry','#8b0000','luxury','Basketball','Patent leather mudguard and carbon fiber spring plate define luxury.',['Patent Leather','Carbon Fiber Plate','Full-Length Air','Translucent Outsole'],stdSizes,4.9,1845,true,true,[{name:'Cherry',hex:'#8b0000',secondary:'#ffffff'},{name:'Concord',hex:'#1a1a6e',secondary:'#ffffff'}]),
  makeSneaker(14,'Nike Alphafly 3','Nike',23699,null,'Volt/Black','#ccff00','sport','Running','Designed for marathon racing with ZoomX and Air Zoom pods.',['ZoomX Foam','Air Zoom Pods','Carbon Plate','Atomknit Upper'],stdSizes,4.8,234,true,false,[{name:'Volt/Black',hex:'#ccff00',secondary:'#1a1a1a'},{name:'White/Pink',hex:'#ffffff',secondary:'#ff69b4'}]),
  makeSneaker(15,'Air Max 1','Nike',12399,null,'Anniversary Red','#cc0000','casual','Lifestyle','The original Air Max that started the visible air revolution in 1987.',['Visible Air Unit','Suede/Mesh Upper','Rubber Outsole','EVA Midsole'],stdSizes,4.7,2456,false,false,[{name:'Anniversary Red',hex:'#cc0000',secondary:'#ffffff'},{name:'Obsidian',hex:'#1a2744',secondary:'#ffffff'}]),
  makeSneaker(16,'Nike ACG Mountain Fly 2','Nike',15799,null,'Gridiron','#555555','sport','Trail','Built for scrambles and technical trails with React foam.',['React Foam','Ripstop Upper','All-Terrain Outsole','Gusseted Tongue'],stdSizes,4.5,178,true,false,[{name:'Gridiron',hex:'#555555',secondary:'#34d399'},{name:'Black/Olive',hex:'#1a1a1a',secondary:'#556b2f'}]),
  makeSneaker(17,'Nike Cortez','Nike',7499,null,'White/Red','#ffffff','casual','Lifestyle','The legendary running shoe turned cultural icon since 1972.',['Leather Upper','Full-Length Foam','Herringbone Outsole','Classic Design'],stdSizes,4.4,3421,false,false,[{name:'White/Red',hex:'#ffffff',secondary:'#cc0000'},{name:'Black/White',hex:'#1a1a1a',secondary:'#ffffff'}]),
  makeSneaker(18,'Air Huarache','Nike',10799,null,'Triple White','#ffffff','casual','Lifestyle','Neoprene inner sleeve for a sock-like fit with visible Air unit.',['Neoprene Sleeve','Visible Air','Rubber Outsole','Dynamic Fit'],stdSizes,4.5,1234,false,false,[{name:'Triple White',hex:'#ffffff',secondary:'#e0e0e0'},{name:'Triple Black',hex:'#0a0a0a',secondary:'#1a1a1a'}]),
  makeSneaker(19,'Nike Zoom Fly 6','Nike',14099,null,'Lime Blast','#00ff00','sport','Running','Responsive ZoomX foam with a carbon fiber plate for tempo runs.',['ZoomX Foam','Carbon Plate','Translucent Upper','Rubber Outsole'],stdSizes,4.6,321,true,false,[{name:'Lime Blast',hex:'#00ff00',secondary:'#1a1a1a'},{name:'White/Black',hex:'#ffffff',secondary:'#1a1a1a'}]),
  makeSneaker(20,'Nike Killshot 2','Nike',8299,null,'Sail/Gum','#f5f0e6','casual','Lifestyle','Clean canvas upper with gum rubber sole for everyday wear.',['Canvas Upper','Gum Rubber Sole','Suede Overlays','Flat Laces'],stdSizes,4.4,876,false,false,[{name:'Sail/Gum',hex:'#f5f0e6',secondary:'#d4a654'},{name:'Grey/Gum',hex:'#8a8a8a',secondary:'#d4a654'}]),

  // ─── ADIDAS (15) ─────────────────────────────────
  makeSneaker(21,'Ultra Boost 24','Adidas',16599,18299,'Cloud White','#f5f5f0','sport','Running','Unrivaled energy return with upgraded BOOST midsole technology.',['BOOST Midsole','Primeknit+ Upper','Continental Outsole','Torsion System'],stdSizes,4.7,287,true,true,[{name:'Cloud White',hex:'#f5f5f0',secondary:'#cccccc'},{name:'Core Black',hex:'#0a0a0a',secondary:'#333333'},{name:'Mint Rush',hex:'#34d399',secondary:'#ffffff'}]),
  makeSneaker(22,'Yeezy Slide Onyx','Adidas',12399,null,'Onyx','#2d2d2d','casual','Slides','EVA foam construction for a lightweight feel with a bold silhouette.',['EVA Foam','Lightweight Build','Contoured Footbed'],smSizes,4.5,892,false,true,[{name:'Onyx',hex:'#2d2d2d',secondary:'#1a1a1a'},{name:'Bone',hex:'#e8dcc8',secondary:'#d4c4a8'}]),
  makeSneaker(23,'Forum Low','Adidas',9099,null,'Cloud White/Green','#f5f5f0','casual','Lifestyle','Born on the basketball court in 1984 with the iconic strap.',['Leather Upper','EVA Midsole','Adjustable Strap','Rubber Outsole'],stdSizes,4.4,312,false,false,[{name:'Cloud White/Green',hex:'#f5f5f0',secondary:'#34d399'},{name:'White/Blue',hex:'#f5f5f0',secondary:'#4263eb'}]),
  makeSneaker(24,'Samba OG','Adidas',9099,null,'White/Black','#ffffff','casual','Lifestyle','The iconic indoor football shoe turned streetwear staple since 1950.',['Leather Upper','Suede T-Toe','Gum Outsole','EVA Midsole'],stdSizes,4.8,4567,false,true,[{name:'White/Black',hex:'#ffffff',secondary:'#1a1a1a'},{name:'Black/White',hex:'#1a1a1a',secondary:'#ffffff'},{name:'Green/Gum',hex:'#2d5016',secondary:'#d4a654'}]),
  makeSneaker(25,'Gazelle Indoor','Adidas',9999,null,'Blue/White','#1a3cc7','casual','Lifestyle','Premium suede upper with archive-inspired design.',['Suede Upper','Gum Outsole','Trefoil Tongue','OrthoLite Sockliner'],stdSizes,4.6,1234,true,true,[{name:'Blue/White',hex:'#1a3cc7',secondary:'#ffffff'},{name:'Red/White',hex:'#cc0000',secondary:'#ffffff'}]),
  makeSneaker(26,'Adizero Adios Pro 4','Adidas',20699,null,'Gold/Black','#ffd700','sport','Running','Carbon-plated racing shoe with LIGHTSTRIKE PRO foam.',['LIGHTSTRIKE PRO','Carbon Rods','CONTINENTAL Outsole','Celermesh Upper'],stdSizes,4.8,156,true,false,[{name:'Gold/Black',hex:'#ffd700',secondary:'#1a1a1a'},{name:'White/Solar Red',hex:'#ffffff',secondary:'#ff4444'}]),
  makeSneaker(27,'NMD_R1','Adidas',12399,null,'Core Black','#0a0a0a','street','Lifestyle','BOOST cushioning with signature midsole plugs for urban energy.',['BOOST Midsole','Primeknit Upper','EVA Plugs','Rubber Outsole'],stdSizes,4.5,2345,false,false,[{name:'Core Black',hex:'#0a0a0a',secondary:'#1a1a1a'},{name:'White/Red',hex:'#ffffff',secondary:'#cc0000'}]),
  makeSneaker(28,'Superstar','Adidas',8299,null,'White/Black','#ffffff','casual','Lifestyle','The shell-toe icon that bridged sport and street culture.',['Leather Upper','Shell Toe','Rubber Outsole','Herringbone Traction'],stdSizes,4.6,6789,false,false,[{name:'White/Black',hex:'#ffffff',secondary:'#1a1a1a'},{name:'Black/White',hex:'#1a1a1a',secondary:'#ffffff'}]),
  makeSneaker(29,'Yeezy 350 V2','Adidas',20699,null,'Beluga','#8a7e72','street','Lifestyle','Primeknit upper on full-length BOOST for unmatched comfort.',['BOOST Sole','Primeknit Upper','TPU Sidewall','Rope Laces'],stdSizes,4.7,3456,false,true,[{name:'Beluga',hex:'#8a7e72',secondary:'#ff4444'},{name:'Zebra',hex:'#ffffff',secondary:'#1a1a1a'}]),
  makeSneaker(30,'Terrex Free Hiker 2','Adidas',18299,null,'Olive/Black','#556b2f','sport','Trail','BOOST midsole meets Continental outsole for all-terrain performance.',['BOOST Midsole','Continental Outsole','GORE-TEX','Primeknit Upper'],stdSizes,4.6,289,true,false,[{name:'Olive/Black',hex:'#556b2f',secondary:'#1a1a1a'},{name:'Grey/Orange',hex:'#8a8a8a',secondary:'#fb923c'}]),
  makeSneaker(31,'Campus 00s','Adidas',8699,null,'Dark Green','#2d5016','casual','Lifestyle','Oversized proportions bring modern chunky vibes to a classic.',['Suede Upper','Rubber Outsole','OrthoLite Sockliner','Serrated 3-Stripes'],stdSizes,4.5,1890,true,true,[{name:'Dark Green',hex:'#2d5016',secondary:'#ffffff'},{name:'Black/White',hex:'#1a1a1a',secondary:'#ffffff'}]),
  makeSneaker(32,'Stan Smith','Adidas',7899,null,'White/Green','#ffffff','casual','Lifestyle','Clean tennis heritage with perforated 3-Stripes.',['Leather Upper','Rubber Outsole','OrthoLite Sockliner','Perforated 3-Stripes'],stdSizes,4.5,5678,false,false,[{name:'White/Green',hex:'#ffffff',secondary:'#34d399'},{name:'White/Navy',hex:'#ffffff',secondary:'#1a2744'}]),
  makeSneaker(33,'Adilette Comfort','Adidas',3299,null,'Core Black','#0a0a0a','casual','Slides','Cushioned Cloudfoam slides for post-workout recovery.',['Cloudfoam Plus','Bandage Upper','Contoured Footbed','Quick-Dry Lining'],smSizes,4.3,3456,false,false,[{name:'Core Black',hex:'#0a0a0a',secondary:'#1a1a1a'},{name:'White',hex:'#ffffff',secondary:'#e0e0e0'}]),
  makeSneaker(34,'Ultra Boost Light','Adidas',15799,null,'Solar Orange','#fb923c','sport','Running','30% lighter BOOST foam for an ultra-responsive feel.',['Light BOOST','Primeknit Upper','Continental Outsole','Linear Energy Push'],stdSizes,4.7,567,true,false,[{name:'Solar Orange',hex:'#fb923c',secondary:'#1a1a1a'},{name:'White/Green',hex:'#ffffff',secondary:'#34d399'}]),
  makeSneaker(35,'Spezial','Adidas',9099,null,'Light Blue','#87ceeb','casual','Lifestyle','Archive handball shoe with gum sole and suede upper.',['Suede Upper','Gum Outsole','EVA Midsole','T-Toe Overlay'],stdSizes,4.6,2345,true,true,[{name:'Light Blue',hex:'#87ceeb',secondary:'#ffffff'},{name:'Red/White',hex:'#cc0000',secondary:'#ffffff'}]),

  // ─── NEW BALANCE (12) ────────────────────────────
  makeSneaker(36,'990v6','New Balance',18299,null,'Grey','#8a8a8a','casual','Lifestyle','Dual-density ENCAP midsole with premium pigskin suede.',['ENCAP Midsole','FuelCell Foam','Pigskin Suede','Breathable Mesh'],stdSizes,4.8,456,true,false,[{name:'Grey',hex:'#8a8a8a',secondary:'#cccccc'},{name:'Navy',hex:'#1a2744',secondary:'#8a8a8a'}]),
  makeSneaker(37,'550','New Balance',9999,null,'White/Green','#ffffff','casual','Lifestyle','Retro basketball silhouette with clean leather upper.',['Leather Upper','Rubber Outsole','Perforated Toe','Padded Collar'],stdSizes,4.7,3456,false,true,[{name:'White/Green',hex:'#ffffff',secondary:'#2d5016'},{name:'White/Navy',hex:'#ffffff',secondary:'#1a2744'},{name:'White/Red',hex:'#ffffff',secondary:'#cc0000'}]),
  makeSneaker(38,'2002R','New Balance',12399,null,'Rain Cloud','#b0b0b0','casual','Lifestyle','Progressive design with N-ERGY cushioning technology.',['N-ERGY Cushioning','ABZORB SBS','Suede/Mesh','Stability Web'],stdSizes,4.6,1234,true,true,[{name:'Rain Cloud',hex:'#b0b0b0',secondary:'#8a8a8a'},{name:'Black/Phantom',hex:'#1a1a1a',secondary:'#2d2d2d'}]),
  makeSneaker(39,'574','New Balance',7499,null,'Navy/Grey','#1a2744','casual','Lifestyle','The iconic everyday sneaker with ENCAP midsole.',['ENCAP Midsole','Suede/Mesh Upper','Rubber Outsole','EVA Foam'],stdSizes,4.5,7890,false,false,[{name:'Navy/Grey',hex:'#1a2744',secondary:'#8a8a8a'},{name:'Grey/White',hex:'#8a8a8a',secondary:'#ffffff'}]),
  makeSneaker(40,'FuelCell SC Elite v4','New Balance',22799,null,'Neon Dragonfly','#00ffcc','sport','Running','Carbon plate racer with FuelCell foam for race day.',['FuelCell Foam','Carbon Plate','Engineered Mesh','Rubber Outsole'],stdSizes,4.8,123,true,false,[{name:'Neon Dragonfly',hex:'#00ffcc',secondary:'#1a1a1a'},{name:'White/Red',hex:'#ffffff',secondary:'#cc0000'}]),
  makeSneaker(41,'1906R','New Balance',14099,null,'Silver Metallic','#c0c0c0','casual','Lifestyle','Y2K-inspired runner with N-ERGY and ABZORB tech.',['N-ERGY','ABZORB','Mesh/Synthetic Upper','Stability Web'],stdSizes,4.6,678,false,true,[{name:'Silver Metallic',hex:'#c0c0c0',secondary:'#ffffff'},{name:'Black',hex:'#1a1a1a',secondary:'#c0c0c0'}]),
  makeSneaker(42,'9060','New Balance',12399,null,'Sea Salt','#f5f0e6','casual','Lifestyle','Warped design language with chunky proportions and suede overlays.',['ABZORB Midsole','Suede Upper','Rubber Outsole','Mesh Panels'],stdSizes,4.7,2345,true,true,[{name:'Sea Salt',hex:'#f5f0e6',secondary:'#c0bcb7'},{name:'Arctic Grey',hex:'#b0b0b0',secondary:'#e0e0e0'}]),
  makeSneaker(43,'530','New Balance',8299,null,'White/Silver','#ffffff','casual','Lifestyle','Retro running design with ABZORB cushioning for everyday comfort.',['ABZORB Midsole','Mesh Upper','Rubber Outsole','Synthetic Overlays'],stdSizes,4.4,1567,false,false,[{name:'White/Silver',hex:'#ffffff',secondary:'#c0c0c0'},{name:'Black/Silver',hex:'#1a1a1a',secondary:'#c0c0c0'}]),
  makeSneaker(44,'Fresh Foam X More v5','New Balance',13699,null,'Black/Lime','#1a1a1a','sport','Running','Maximum cushioning for long-distance comfort.',['Fresh Foam X','Engineered Mesh','Rock Stop Plate','Rubber Outsole'],stdSizes,4.6,345,true,false,[{name:'Black/Lime',hex:'#1a1a1a',secondary:'#ccff00'},{name:'White/Grey',hex:'#ffffff',secondary:'#8a8a8a'}]),
  makeSneaker(45,'327','New Balance',8299,null,'Moonbeam','#f0ece6','casual','Lifestyle','Asymmetric design inspired by 70s running with oversized N logo.',['EVA Midsole','Suede/Nylon Upper','Rubber Outsole','Asymmetric Design'],stdSizes,4.5,2345,false,false,[{name:'Moonbeam',hex:'#f0ece6',secondary:'#c0bcb7'},{name:'Sea Salt/Blue',hex:'#f5f0e6',secondary:'#87ceeb'}]),
  makeSneaker(46,'1080v14','New Balance',13299,null,'Storm Blue','#4a6fa5','sport','Running','Fresh Foam X cushioning for premium daily training.',['Fresh Foam X','Hypoknit Upper','Blown Rubber Outsole','Ortholite Sockliner'],stdSizes,4.7,890,true,false,[{name:'Storm Blue',hex:'#4a6fa5',secondary:'#ffffff'},{name:'Black/Silver',hex:'#1a1a1a',secondary:'#c0c0c0'}]),
  makeSneaker(47,'650','New Balance',11599,null,'White/Red','#ffffff','casual','Basketball','Retro high-top basketball shoe with ankle support.',['Leather Upper','C-CAP Midsole','Rubber Outsole','Ankle Strap'],stdSizes,4.5,456,false,false,[{name:'White/Red',hex:'#ffffff',secondary:'#cc0000'},{name:'White/Navy',hex:'#ffffff',secondary:'#1a2744'}]),

  // ─── ASICS (8) ───────────────────────────────────
  makeSneaker(48,'Gel-Kayano 14','Asics',13299,null,'Silver/White','#c0c0c0','sport','Running','Retro Y2K aesthetics with modern GEL technology.',['GEL Technology','Trusstic System','IGS Technology','Blown Rubber Outsole'],stdSizes,4.6,198,false,true,[{name:'Silver/White',hex:'#c0c0c0',secondary:'#ffffff'},{name:'Black/Silver',hex:'#1a1a1a',secondary:'#c0c0c0'}]),
  makeSneaker(49,'Gel-1130','Asics',9999,null,'White/Silver','#ffffff','casual','Lifestyle','2000s running aesthetic for everyday streetwear.',['GEL Cushioning','Mesh Upper','Trusstic System','Rubber Outsole'],stdSizes,4.5,1678,true,true,[{name:'White/Silver',hex:'#ffffff',secondary:'#c0c0c0'},{name:'Oyster Grey',hex:'#d4c8b4',secondary:'#8a7e72'}]),
  makeSneaker(50,'Gel-NYC','Asics',12399,null,'Oatmeal/Obsidian','#d4c4a8','casual','Lifestyle','Hybrid design combining GT-2160 and MC Plus V shapes.',['GEL Technology','Suede/Mesh Upper','Trusstic','EVA Midsole'],stdSizes,4.7,567,true,true,[{name:'Oatmeal/Obsidian',hex:'#d4c4a8',secondary:'#1a2744'},{name:'White/Ivy',hex:'#ffffff',secondary:'#556b2f'}]),
  makeSneaker(51,'Novablast 4','Asics',11599,null,'Illusion Blue','#4a6fa5','sport','Running','FF BLAST PLUS Eco cushioning for bouncy training runs.',['FF BLAST PLUS Eco','Engineered Mesh','AHAR Outsole','Trusstic'],stdSizes,4.6,678,true,false,[{name:'Illusion Blue',hex:'#4a6fa5',secondary:'#ffffff'},{name:'Black/Pure Silver',hex:'#1a1a1a',secondary:'#c0c0c0'}]),
  makeSneaker(52,'Gel-Nimbus 26','Asics',13299,null,'French Blue','#0055a4','sport','Running','PureGEL technology for soft, smooth underfoot comfort.',['PureGEL','FF BLAST PLUS Eco','Engineered Knit','AHAR Plus'],stdSizes,4.7,890,false,false,[{name:'French Blue',hex:'#0055a4',secondary:'#ffffff'},{name:'Black/Black',hex:'#0a0a0a',secondary:'#1a1a1a'}]),
  makeSneaker(53,'GT-2160','Asics',9999,null,'White/Pure Silver','#ffffff','casual','Lifestyle','2010s running silhouette reborn as fashion staple.',['GEL Technology','Duomax Support','Trusstic System','AHAR Outsole'],stdSizes,4.5,1234,false,true,[{name:'White/Pure Silver',hex:'#ffffff',secondary:'#c0c0c0'},{name:'Dark Taupe',hex:'#8a7e72',secondary:'#d4c4a8'}]),
  makeSneaker(54,'Gel-Quantum 360 VII','Asics',15799,null,'Black/Sour Yuzu','#0a0a0a','sport','Running','360 degrees of GEL cushioning wraps the entire midsole.',['360 GEL','Mono-Sock Fit','TRUSSTIC','Durable Outsole'],stdSizes,4.5,234,false,false,[{name:'Black/Sour Yuzu',hex:'#0a0a0a',secondary:'#e8e800'},{name:'White/White',hex:'#ffffff',secondary:'#e0e0e0'}]),
  makeSneaker(55,'Metaspeed Sky+ Paris','Asics',20699,null,'Safety Yellow','#e8e800','sport','Running','Carbon plate racer designed for stride-type runners.',['FF TURBO PLUS','Carbon Plate','Motion Wrap Upper','ASICSGRIP'],stdSizes,4.8,145,true,false,[{name:'Safety Yellow',hex:'#e8e800',secondary:'#1a1a1a'},{name:'Sunrise Red',hex:'#ff4444',secondary:'#ffffff'}]),

  // ─── HOKA (6) ────────────────────────────────────
  makeSneaker(56,'Bondi 8','HOKA',13699,null,'Black/Black','#0a0a0a','sport','Running','Maximum cushion for maximum comfort mile after mile.',['Full EVA Midsole','Meta-Rocker','Ortholite Sockliner','Durabrasion Outsole'],stdSizes,4.7,834,false,true,[{name:'Black/Black',hex:'#0a0a0a',secondary:'#1a1a1a'},{name:'White/White',hex:'#ffffff',secondary:'#f0f0f0'}]),
  makeSneaker(57,'Clifton 9','HOKA',11999,null,'Cyclamen/Sweet Lilac','#cc66cc','sport','Running','Balanced cushioning with improved breathability.',['CMEVA Foam','Engineered Mesh','Rubber Outsole','Ultra-Light Design'],stdSizes,4.7,1234,true,true,[{name:'Cyclamen',hex:'#cc66cc',secondary:'#dda0dd'},{name:'White/Black',hex:'#ffffff',secondary:'#1a1a1a'}]),
  makeSneaker(58,'Speedgoat 6','HOKA',12899,null,'Real Teal','#008080','sport','Trail','Vibram Megagrip outsole for aggressive trail traction.',['CMEVA Foam','Vibram Megagrip','Recycled Mesh','Late-Stage Meta-Rocker'],stdSizes,4.8,456,true,false,[{name:'Real Teal',hex:'#008080',secondary:'#1a1a1a'},{name:'Castlerock',hex:'#555555',secondary:'#1a1a1a'}]),
  makeSneaker(59,'Mach 6','HOKA',11599,null,'White/Nimbus Cloud','#ffffff','sport','Running','Supercritical foam for a responsive, lightweight ride.',['PEBA Foam','Engineered Mesh','Rubber Outsole','Streamlined Design'],stdSizes,4.6,567,true,true,[{name:'White/Nimbus Cloud',hex:'#ffffff',secondary:'#d0d0d0'},{name:'Black/White',hex:'#1a1a1a',secondary:'#ffffff'}]),
  makeSneaker(60,'Transport','HOKA',11999,null,'Black/Black','#0a0a0a','casual','Lifestyle','Versatile design transitions from trails to streets.',['CMEVA Foam','Vibram EcoStep','Recycled Materials','Flat-Knit Upper'],stdSizes,4.5,345,false,false,[{name:'Black/Black',hex:'#0a0a0a',secondary:'#1a1a1a'},{name:'Dune/Eggnog',hex:'#c4ae78',secondary:'#f5f0e6'}]),
  makeSneaker(61,'Arahi 7','HOKA',11599,null,'Outer Space/White','#2d2d3d','sport','Running','J-Frame support for overpronation without heavy medial post.',['J-Frame Support','CMEVA Foam','Engineered Mesh','Rubber Outsole'],stdSizes,4.6,289,false,false,[{name:'Outer Space/White',hex:'#2d2d3d',secondary:'#ffffff'},{name:'Blue Graphite',hex:'#4a5568',secondary:'#87ceeb'}]),

  // ─── ON RUNNING (5) ──────────────────────────────
  makeSneaker(62,'Cloudmonster 2','On',14899,null,'Undyed/Frost','#e8e4df','sport','Running','CloudTec Phase technology for smooth transitions.',['CloudTec Phase','Helion Superfoam','Speedboard','Engineered Mesh'],stdSizes,4.6,167,true,false,[{name:'Undyed/Frost',hex:'#e8e4df',secondary:'#c0bcb7'},{name:'Eclipse/Turmeric',hex:'#1a1a2e',secondary:'#e8a317'}]),
  makeSneaker(63,'Cloud 5','On',12399,null,'All White','#ffffff','casual','Lifestyle','Lightweight everyday shoe with CloudTec cushioning.',['CloudTec','Speedboard','Engineered Mesh','Zero-Gravity Foam'],stdSizes,4.5,2345,false,true,[{name:'All White',hex:'#ffffff',secondary:'#e0e0e0'},{name:'All Black',hex:'#0a0a0a',secondary:'#1a1a1a'}]),
  makeSneaker(64,'Cloudstratus 3','On',14099,null,'Black/Rock','#0a0a0a','sport','Running','Double layer CloudTec for maximum cushioning.',['Dual CloudTec','Helion Superfoam','Speedboard','Recycled Materials'],stdSizes,4.6,456,true,false,[{name:'Black/Rock',hex:'#0a0a0a',secondary:'#555555'},{name:'Frost/Creek',hex:'#e8e4df',secondary:'#5f9ea0'}]),
  makeSneaker(65,'Cloudsurfer 7','On',13299,null,'Cobalt/Flame','#0047ab','sport','Running','CloudTec Phase for training and racing versatility.',['CloudTec Phase','Helion Superfoam','Speedboard','Engineered Mesh'],stdSizes,4.7,234,true,true,[{name:'Cobalt/Flame',hex:'#0047ab',secondary:'#ff4500'},{name:'Aloe/Frost',hex:'#34d399',secondary:'#e8e4df'}]),
  makeSneaker(66,'Cloudnova','On',13299,null,'Sand/Magnet','#c4ae78','casual','Lifestyle','Street-ready design with CloudTec cushioning.',['CloudTec','Recycled Upper','Rubber Outsole','Speed Lacing'],stdSizes,4.4,567,false,false,[{name:'Sand/Magnet',hex:'#c4ae78',secondary:'#555555'},{name:'White/Rust',hex:'#ffffff',secondary:'#b87333'}]),

  // ─── SALOMON (5) ─────────────────────────────────
  makeSneaker(67,'XT-6','Salomon',16599,null,'Vanilla Ice','#f5f0e6','sport','Trail','Ultra-distance trail running meets urban streets.',['Contagrip MA','Advanced Chassis','SensiFit','Quicklace'],stdSizes,4.8,421,true,true,[{name:'Vanilla Ice',hex:'#f5f0e6',secondary:'#c0bcb7'},{name:'Black/Phantom',hex:'#0a0a0a',secondary:'#2d2d2d'}]),
  makeSneaker(68,'XT-4 OG','Salomon',16599,null,'Pewter/Ebony','#899499','sport','Trail','Aggressive silhouette from competitive trail heritage.',['Contagrip','SensiFit','Chassis System','Quicklace'],stdSizes,4.7,345,false,true,[{name:'Pewter/Ebony',hex:'#899499',secondary:'#555555'},{name:'Black/Silver',hex:'#1a1a1a',secondary:'#c0c0c0'}]),
  makeSneaker(69,'ACS Pro','Salomon',15799,null,'White/Vanilla','#ffffff','sport','Trail','Advanced Chassis System with Contagrip outsole.',['Contagrip MA','ACS Chassis','SensiFit','Ortholite','Quicklace'],stdSizes,4.6,234,true,false,[{name:'White/Vanilla',hex:'#ffffff',secondary:'#f5f0e6'},{name:'Black/Black',hex:'#0a0a0a',secondary:'#1a1a1a'}]),
  makeSneaker(70,'Speedcross 6','Salomon',11599,null,'Black/Fiery Red','#1a1a1a','sport','Trail','Deep lugs and aggressive grip for muddy trail running.',['Contagrip MA','EnergyCell+','SensiFit','Quicklace','Anti-Debris Mesh'],stdSizes,4.7,678,false,false,[{name:'Black/Fiery Red',hex:'#1a1a1a',secondary:'#cc0000'},{name:'Delphinium Blue',hex:'#6495ed',secondary:'#ffffff'}]),
  makeSneaker(71,'RX Slide 3.0','Salomon',5399,null,'Black','#0a0a0a','casual','Slides','Recovery slide with cushioned EVA footbed.',['EVA Footbed','Soft Material Upper','Non-Marking Outsole','Easy Slip-On'],smSizes,4.3,890,false,false,[{name:'Black',hex:'#0a0a0a',secondary:'#1a1a1a'},{name:'Vanilla',hex:'#f5f0e6',secondary:'#c0bcb7'}]),

  // ─── PUMA (5) ────────────────────────────────────
  makeSneaker(72,'Puma Suede XL','Puma',7499,null,'Clyde Royal/White','#1a3cc7','casual','Lifestyle','Upsized Suede with wider proportions and thicker sole.',['Suede Upper','Rubber Outsole','SoftFoam Sockliner','Formstrip'],stdSizes,4.2,203,true,false,[{name:'Clyde Royal/White',hex:'#1a3cc7',secondary:'#ffffff'},{name:'Black/White',hex:'#1a1a1a',secondary:'#ffffff'}]),
  makeSneaker(73,'Speedcat OG','Puma',9099,null,'Black','#0a0a0a','casual','Motorsport','Low-profile motorsport icon from the racetrack.',['Suede Upper','Rubber Outsole','Low Profile','Puma Cat Logo'],stdSizes,4.5,567,true,true,[{name:'Black',hex:'#0a0a0a',secondary:'#1a1a1a'},{name:'White/Red',hex:'#ffffff',secondary:'#cc0000'}]),
  makeSneaker(74,'RS-X','Puma',9999,null,'White/Royal','#ffffff','casual','Lifestyle','Chunky running system design from the 80s.',['Running System Tech','Mesh/Leather Upper','Rubber Outsole','Chunky Sole'],stdSizes,4.4,890,false,false,[{name:'White/Royal',hex:'#ffffff',secondary:'#1a3cc7'},{name:'Black/Red',hex:'#1a1a1a',secondary:'#cc0000'}]),
  makeSneaker(75,'Palermo','Puma',7099,null,'Light Straw','#e8dcc8','casual','Lifestyle','Terrace culture inspired with T-toe suede overlay.',['Suede Upper','Rubber Outsole','T-Toe Design','Gum Sole'],stdSizes,4.5,678,true,true,[{name:'Light Straw',hex:'#e8dcc8',secondary:'#d4c4a8'},{name:'Blue/Gum',hex:'#87ceeb',secondary:'#d4a654'}]),
  makeSneaker(76,'Deviate Nitro 3','Puma',13299,null,'Fire Orchid','#e25822','sport','Running','NITRO foam with carbon INNOPLATE for training.',['NITRO Foam','INNOPLATE Carbon','PUMAGRIP','Engineered Mesh'],stdSizes,4.6,234,true,false,[{name:'Fire Orchid',hex:'#e25822',secondary:'#1a1a1a'},{name:'Ultra Blue',hex:'#0066ff',secondary:'#ffffff'}]),

  // ─── CONVERSE (4) ────────────────────────────────
  makeSneaker(77,'Chuck 70 Hi','Converse',7499,null,'Parchment','#f5f0e0','casual','Lifestyle','Vintage colors and premium canvas on the elevated classic.',['Premium Canvas','OrthoLite Insole','Egret Midsole','Rubber Outsole'],[5,6,...stdSizes],4.5,1456,false,false,[{name:'Parchment',hex:'#f5f0e0',secondary:'#1a1a1a'},{name:'Black',hex:'#1a1a1a',secondary:'#ffffff'}]),
  makeSneaker(78,'Chuck Taylor All Star','Converse',4999,null,'Optical White','#ffffff','casual','Lifestyle','The original basketball sneaker icon since 1917.',['Canvas Upper','Rubber Outsole','Vulcanized Construction','Ankle Patch'],[5,6,...stdSizes],4.4,12345,false,false,[{name:'Optical White',hex:'#ffffff',secondary:'#cc0000'},{name:'Black',hex:'#1a1a1a',secondary:'#ffffff'}]),
  makeSneaker(79,'One Star Pro','Converse',7099,null,'Black/White','#1a1a1a','street','Skateboarding','Suede skate shoe with CONS CX cushioning.',['Suede Upper','CONS CX Foam','Rubber Outsole','Padded Collar'],[6,...stdSizes],4.5,678,false,false,[{name:'Black/White',hex:'#1a1a1a',secondary:'#ffffff'},{name:'Egret',hex:'#f5f0e0',secondary:'#1a1a1a'}]),
  makeSneaker(80,'Run Star Hike','Converse',9999,null,'White/Black','#ffffff','street','Lifestyle','Platform-elevated Chuck Taylor for bold streetwear.',['Canvas Upper','Jagged Sole','Platform Height','Rubber Outsole'],[5,6,...stdSizes],4.3,1234,false,true,[{name:'White/Black',hex:'#ffffff',secondary:'#1a1a1a'},{name:'Black/White',hex:'#1a1a1a',secondary:'#ffffff'}]),

  // ─── VANS (4) ────────────────────────────────────
  makeSneaker(81,'Old Skool','Vans',6199,null,'Black/White','#1a1a1a','street','Skateboarding','Original sidestripe shoe with legendary waffle outsole.',['Suede/Canvas Upper','Waffle Outsole','Padded Collar','Vulcanized Construction'],[6,...stdSizes],4.6,3201,false,false,[{name:'Black/White',hex:'#1a1a1a',secondary:'#ffffff'},{name:'Navy/White',hex:'#1a2744',secondary:'#ffffff'}]),
  makeSneaker(82,'Sk8-Hi','Vans',6599,null,'Black/Black','#0a0a0a','street','Skateboarding','High-top with padded ankle support for skateboarding.',['Canvas/Suede Upper','Waffle Outsole','Padded Collar','Jazz Stripe'],[6,...stdSizes],4.5,2345,false,false,[{name:'Black/Black',hex:'#0a0a0a',secondary:'#1a1a1a'},{name:'White',hex:'#ffffff',secondary:'#e0e0e0'}]),
  makeSneaker(83,'Authentic','Vans',4599,null,'True White','#ffffff','casual','Lifestyle','The original since 1966 with metal eyelets and rubber waffle outsole.',['Canvas Upper','Waffle Outsole','Metal Eyelets','Vulcanized Construction'],[5,6,...stdSizes],4.3,4567,false,false,[{name:'True White',hex:'#ffffff',secondary:'#e0e0e0'},{name:'Black',hex:'#1a1a1a',secondary:'#1a1a1a'}]),
  makeSneaker(84,'Knu Skool','Vans',7899,null,'Black/White','#1a1a1a','street','Lifestyle','Puffed-up reimagining of the classic Old Skool silhouette.',['Leather/Suede Upper','Puffed Panels','Waffle Outsole','SickStick Grip'],stdSizes,4.6,1234,true,true,[{name:'Black/White',hex:'#1a1a1a',secondary:'#ffffff'},{name:'White/Gum',hex:'#ffffff',secondary:'#d4a654'}]),

  // ─── REEBOK (4) ──────────────────────────────────
  makeSneaker(85,'Club C 85','Reebok',7099,null,'White/Green','#ffffff','casual','Lifestyle','Soft leather upper and subtle vintage styling.',['Leather Upper','Die-Cut EVA','Rubber Outsole','Padded Foam Sockliner'],stdSizes,4.4,567,false,false,[{name:'White/Green',hex:'#ffffff',secondary:'#34d399'},{name:'White/Navy',hex:'#ffffff',secondary:'#1a2744'}]),
  makeSneaker(86,'Classic Leather','Reebok',6599,null,'White/Gum','#ffffff','casual','Lifestyle','Heritage running style with soft full-grain leather.',['Leather Upper','EVA Midsole','High-Abrasion Outsole','Die-Cut EVA'],stdSizes,4.3,1234,false,false,[{name:'White/Gum',hex:'#ffffff',secondary:'#d4a654'},{name:'Black/Gum',hex:'#1a1a1a',secondary:'#d4a654'}]),
  makeSneaker(87,'Nano X4','Reebok',11599,null,'Core Black','#0a0a0a','sport','Training','CrossFit training shoe with Floatride Energy Foam.',['Floatride Energy','Flexweave Upper','Rubber Outsole','Heel Clip'],stdSizes,4.6,345,true,false,[{name:'Core Black',hex:'#0a0a0a',secondary:'#1a1a1a'},{name:'White/Green',hex:'#ffffff',secondary:'#34d399'}]),
  makeSneaker(88,'Question Mid','Reebok',13299,null,'Red/White','#cc0000','street','Basketball','Allen Iverson signature shoe with Hexalite cushioning.',['Hexalite Cushioning','Leather Upper','Herringbone Outsole','Padded Collar'],stdSizes,4.5,456,false,false,[{name:'Red/White',hex:'#cc0000',secondary:'#ffffff'},{name:'Black',hex:'#1a1a1a',secondary:'#1a1a1a'}]),

  // ─── SAUCONY (4) ─────────────────────────────────
  makeSneaker(89,'Shadow 6000','Saucony',10799,null,'Green/Brown','#2d5016','casual','Lifestyle','Premium suede and mesh with ABZORB cushioning.',['ABZORB Cushioning','Suede/Mesh Upper','Rubber Outsole','EVA Midsole'],stdSizes,4.3,134,false,false,[{name:'Green/Brown',hex:'#2d5016',secondary:'#8B4513'},{name:'Navy/Red',hex:'#1a2744',secondary:'#cc0000'}]),
  makeSneaker(90,'Endorphin Speed 4','Saucony',14099,null,'Vizi Orange','#ff6600','sport','Running','SPEEDROLL technology with nylon plate for speed training.',['PWRRUN PB Foam','Nylon Plate','SPEEDROLL','Engineered Mesh'],stdSizes,4.7,567,true,true,[{name:'Vizi Orange',hex:'#ff6600',secondary:'#1a1a1a'},{name:'Black/White',hex:'#1a1a1a',secondary:'#ffffff'}]),
  makeSneaker(91,'Jazz Original','Saucony',5799,null,'Navy/Off-White','#1a2744','casual','Lifestyle','Classic running-inspired sneaker since 1981.',['Suede/Nylon Upper','EVA Midsole','Rubber Outsole','Padded Collar'],stdSizes,4.3,2345,false,false,[{name:'Navy/Off-White',hex:'#1a2744',secondary:'#f5f0e6'},{name:'Grey/Orange',hex:'#8a8a8a',secondary:'#fb923c'}]),
  makeSneaker(92,'Triumph 22','Saucony',13299,null,'Fog/Bough','#c0c0c0','sport','Running','PWRRUN+ cushioning for maximum comfort daily runs.',['PWRRUN+ Foam','Engineered Mesh','Rubber Outsole','FormFit'],stdSizes,4.6,345,true,false,[{name:'Fog/Bough',hex:'#c0c0c0',secondary:'#556b2f'},{name:'Black/White',hex:'#1a1a1a',secondary:'#ffffff'}]),

  // ─── LUXURY / DESIGNER (8) ───────────────────────
  makeSneaker(93,'Balenciaga Track','Balenciaga',90499,null,'White/Orange','#ffffff','luxury','Designer','Multi-layered construction with 176 individual pieces.',['Multi-Material Upper','Sculpted Sole','Mesh Panels','Logo Details'],[7,8,9,10,11,12],4.3,89,true,false,[{name:'White/Orange',hex:'#ffffff',secondary:'#fb923c'},{name:'Black',hex:'#0a0a0a',secondary:'#2d2d2d'}]),
  makeSneaker(94,'Balenciaga Triple S','Balenciaga',87199,null,'Black/Red','#1a1a1a','luxury','Designer','Triple-stacked sole with vintage running inspiration.',['Triple Sole','Mesh/Leather','Embroidered Logo','Distressed Finish'],[7,8,9,10,11,12],4.2,123,false,false,[{name:'Black/Red',hex:'#1a1a1a',secondary:'#cc0000'},{name:'White',hex:'#ffffff',secondary:'#e0e0e0'}]),
  makeSneaker(95,'Golden Goose Superstar','Golden Goose',49399,null,'White/Star','#ffffff','luxury','Designer','Hand-distressed Italian leather with signature star.',['Italian Leather','Hand-Distressed','Rubber Outsole','Star Patch'],[7,8,9,10,11,12],4.4,234,false,true,[{name:'White/Star',hex:'#ffffff',secondary:'#1a1a1a'},{name:'Silver/Star',hex:'#c0c0c0',secondary:'#1a1a1a'}]),
  makeSneaker(96,'Common Projects Achilles Low','Common Projects',37299,null,'White','#ffffff','luxury','Designer','Minimalist Italian leather with gold serial stamp.',['Italian Napa Leather','Margom Sole','Gold Stamp','Hand-Stitched'],[7,8,9,10,11,12],4.7,456,false,false,[{name:'White',hex:'#ffffff',secondary:'#f5f5f0'},{name:'Black',hex:'#1a1a1a',secondary:'#1a1a1a'}]),
  makeSneaker(97,'Alexander McQueen Oversized','Alexander McQueen',48999,null,'White/Black','#ffffff','luxury','Designer','Exaggerated rubber sole with smooth calf leather.',['Calf Leather','Oversized Sole','Padded Collar','Logo Detail'],[7,8,9,10,11,12],4.3,345,false,true,[{name:'White/Black',hex:'#ffffff',secondary:'#1a1a1a'},{name:'White/Pink',hex:'#ffffff',secondary:'#ff69b4'}]),
  makeSneaker(98,'Maison Margiela Replica','Maison Margiela',41099,null,'Vintage White','#f5f0e6','luxury','Designer','Hand-painted vintage treatment on premium leather.',['Calfskin Leather','Hand-Painted Finish','Rubber Sole','Suede Panels'],[7,8,9,10,11,12],4.5,167,false,false,[{name:'Vintage White',hex:'#f5f0e6',secondary:'#d4c4a8'},{name:'Grey',hex:'#8a8a8a',secondary:'#555555'}]),
  makeSneaker(99,'Off-White Out Of Office','Off-White',45199,null,'White/Black','#ffffff','luxury','Designer','Virgil Abloh signature with iconic zip-tie and quotation marks.',['Leather Upper','Arrow Logo','Zip-Tie Detail','Rubber Outsole'],[7,8,9,10,11,12],4.4,234,true,true,[{name:'White/Black',hex:'#ffffff',secondary:'#1a1a1a'},{name:'Beige/Brown',hex:'#e8dcc8',secondary:'#8B4513'}]),
  makeSneaker(100,'Amiri Skel-Top','Amiri',57699,null,'White/Black','#ffffff','luxury','Designer','Skeleton bone appliqué on premium leather.',['Premium Leather','Bone Appliqué','Rubber Outsole','Padded Collar'],[7,8,9,10,11,12],4.3,89,false,false,[{name:'White/Black',hex:'#ffffff',secondary:'#1a1a1a'},{name:'Black/White',hex:'#1a1a1a',secondary:'#ffffff'}]),

  // ─── BONUS (5 more to hit 105) ───────────────────
  makeSneaker(101,'Mizuno Wave Rider 28','Mizuno',11599,null,'Undyed White','#f5f5f0','sport','Running','MIZUNO ENERZY foam with Wave Plate for smooth transitions.',['ENERZY Foam','Wave Plate','Engineered Mesh','X10 Outsole'],stdSizes,4.6,345,true,false,[{name:'Undyed White',hex:'#f5f5f0',secondary:'#c0bcb7'},{name:'Black/Silver',hex:'#1a1a1a',secondary:'#c0c0c0'}]),
  makeSneaker(102,'Brooks Ghost 16','Brooks',11599,null,'Black/Ebony','#1a1a1a','sport','Running','DNA LOFT v2 cushioning for smooth neutral running.',['DNA LOFT v2','3D Fit Print Upper','Segmented Crash Pad','Rubber Outsole'],stdSizes,4.7,1234,false,false,[{name:'Black/Ebony',hex:'#1a1a1a',secondary:'#2d2d2d'},{name:'White/Oyster',hex:'#ffffff',secondary:'#d4c4a8'}]),
  makeSneaker(103,'Under Armour HOVR Phantom 3','Under Armour',11599,null,'Black/White','#1a1a1a','sport','Running','UA HOVR cushioning returns energy with every step.',['UA HOVR','Warp Upper','Rubber Outsole','Connected Fitness'],stdSizes,4.5,567,false,false,[{name:'Black/White',hex:'#1a1a1a',secondary:'#ffffff'},{name:'White/Halo Grey',hex:'#ffffff',secondary:'#d0d0d0'}]),
  makeSneaker(104,'Merrell Moab Speed 2','Merrell',11599,null,'Black/Multi','#1a1a1a','sport','Trail','Vibram TC5+ sole with FloatPro foam for trail adventures.',['Vibram TC5+','FloatPro Foam','Bellows Tongue','Protective Toe Cap'],stdSizes,4.5,234,true,false,[{name:'Black/Multi',hex:'#1a1a1a',secondary:'#fb923c'},{name:'Olive',hex:'#556b2f',secondary:'#c0bcb7'}]),
  makeSneaker(105,'Diadora N9000','Diadora',9999,null,'White/Foggy Dew','#ffffff','casual','Lifestyle','Italian heritage runner with premium materials.',['Suede/Mesh Upper','EVA Midsole','Rubber Outsole','Padded Collar'],stdSizes,4.4,123,false,false,[{name:'White/Foggy Dew',hex:'#ffffff',secondary:'#c0bcb7'},{name:'Blue/Grey',hex:'#4a6fa5',secondary:'#8a8a8a'}]),
];

const imageUrls = {
  1: ['https://images.unsplash.com/photo-1605340537586-643ed28f5979?auto=format&fit=crop&w=800&q=80'], // Air Nova X
  2: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'], // Jordan 1
  3: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80'], // Dunk Low
  4: ['https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=800&q=80'], // Air Force 1
  5: ['https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=800&q=80'], // Air Max
  21: ['https://images.unsplash.com/photo-1584735174965-48c48d7cdfde?auto=format&fit=crop&w=800&q=80'], // Ultra Boost
  24: ['https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80'], // Samba
  36: ['https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=800&q=80'], // New Balance
};

const defaultImages = [
  'https://images.unsplash.com/photo-1552346154-21d32810baa3?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?auto=format&fit=crop&w=800&q=80'
];

sneakers.forEach((s, index) => {
  const id = index + 1;
  if (imageUrls[id]) {
    s.images = imageUrls[id];
  } else {
    s.images = [defaultImages[index % defaultImages.length]];
  }
});

const seedDB = async () => {
  try {
    const uri = process.env.MONGODB_URI || 'mongodb://localhost:27017/sneakai';
    await mongoose.connect(uri);
    console.log('✅ Connected to MongoDB');

    await Sneaker.deleteMany({});
    console.log('🗑️  Cleared existing sneakers');

    await Sneaker.insertMany(sneakers);
    console.log(`✅ Seeded ${sneakers.length} sneakers`);
    console.log(`   Brands: Nike(20), Adidas(15), New Balance(12), Asics(8), HOKA(6), On(5), Salomon(5), Puma(5), Converse(4), Vans(4), Reebok(4), Saucony(4), Luxury(8), Others(5)`);

    await mongoose.disconnect();
    console.log('✅ Done!');
  } catch (error) {
    console.error('❌ Seed error:', error.message);
    process.exit(1);
  }
};

seedDB();
